#spring.application.name=APPOINTMENT
#server.port=9200
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/hms_appointment_db
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#
## AWS Config
#aws.s3.bucket-name=${S3_BUCKET_NAME}
#aws.s3.region=${S3_REGION}
#aws.access-key=${AWS_ACCESS_KEY}
#aws.secret-key=${AWS_SECRET_KEY}
#
## Archive threshold
#archive.older-than-days=30
#
#twilio.account.sid=${TWILIO_ACCOUNT_SID}
#twilio.auth.token=${TWILIO_AUTH_TOKEN}
#twilio.whatsapp.from=whatsapp:+14155238886
#
#spring.output.ansi.enabled=ALWAYS
#logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n
#
#DOCTOR_NOT_FOUND=Doctor Not Found
#PATIENT_NOT_FOUND= Patient Not Found
#
##spring.cloud.openfeign.circuitbreaker.enabled=true
#spring.cloud.openfeign.circuitbreaker.enabled=false
spring.application.name=APPOINTMENT
server.port=9200

spring.datasource.url=jdbc:postgresql://localhost:5432/hms_appointment_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# AWS Config
aws.s3.bucket-name=${S3_BUCKET_NAME}
aws.s3.region=${S3_REGION:ap-south-1}

# Archive threshold
archive.older-than-days=30

twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp.from=whatsapp:+17372508034

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(${PID:- })%clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n

DOCTOR_NOT_FOUND=Doctor Not Found
PATIENT_NOT_FOUND= Patient Not Found

#spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.enabled=false