spring.application.name=GatewayMS
server.port=9000

# 1. Handle Duplicate Headers (This is important!)
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_UNIQUE

# 2. Global CORS Configuration
# Note: Ensure there are NO spaces after commas in allowedMethods
#spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOriginPatterns=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations[/**].allowCredentials=true

# UserMS Route
spring.cloud.gateway.routes[0].id=UserMS
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=TokenFilter
#spring.cloud.gateway.routes[0].filters[1]=RewritePath=/user/(?<segment>.*), /user/${segment}

# ProfileMS Route
spring.cloud.gateway.routes[1].id=ProfileMS
spring.cloud.gateway.routes[1].uri=lb://PROFILEMS
spring.cloud.gateway.routes[1].predicates[0]=Path=/profile/**,  /api/hospitals/**
#spring.cloud.gateway.routes[1].filters[0]=TokenFilter
#spring.cloud.gateway.routes[1].filters[1]=RewritePath=/user/(?<segment>.*), /user/${segment}

# Appointment Route
spring.cloud.gateway.routes[2].id=APPOINTMENT
spring.cloud.gateway.routes[2].uri=lb://APPOINTMENT
spring.cloud.gateway.routes[2].predicates[0]=Path=/appointment/**, /api/prescriptions/**
#spring.cloud.gateway.routes[2].filters[0]=TokenFilter
#spring.cloud.gateway.routes[2].filters[1]=RewritePath=/user/(?<segment>.*), /user/${segment}

spring.cloud.gateway.routes[3].id=ForgotPasswordMS
spring.cloud.gateway.routes[3].uri=lb://user-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/forgotPassword/**

# AI-Service Route
spring.cloud.gateway.routes[4].id=AI-Service
spring.cloud.gateway.routes[4].uri=lb://AI-Service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/ai/**

# Patient AI Route
spring.cloud.gateway.routes[5].id=PATIENT-AI
spring.cloud.gateway.routes[5].uri=lb://AI-Service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/patient-ai/**

#PharmacyMS
spring.cloud.gateway.routes[6].id=PharmacyMS
spring.cloud.gateway.routes[6].uri=lb://PharmacyMS
spring.cloud.gateway.routes[6].predicates[0]=Path=/pharmacy/**

# HealthPackage Route (must be LAST since it's a catch-all /api/**)
spring.cloud.gateway.routes[7].id=HEALTH-PACKAGE-MS
spring.cloud.gateway.routes[7].uri=lb://HEALTH-PACKAGE-MS
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/**

# JWT
jwt.secret=${JWT_SECRET}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n
